# One Dark system monitor theme.

[flags]
rate = "1s"
default_time_value = "60s"
hide_table_gap = true
show_table_scroll_position = true
memory_legend = "top-right"
network_legend = "top-right"

[styles]
theme = "default"

[styles.cpu]
all_entry_color = "#61afef"
avg_entry_color = "#e5c07b"
cpu_core_colors = [
  "#61afef",
  "#98c379",
  "#c678dd",
  "#56b6c2",
  "#e5c07b",
  "#e06c75",
  "#d19a66",
  "#abb2bf",
]

[styles.memory]
ram_color = "#c678dd"
cache_color = "#61afef"
swap_color = "#e5c07b"
arc_color = "#56b6c2"
gpu_colors = ["#61afef", "#98c379", "#c678dd", "#56b6c2", "#e5c07b", "#e06c75"]

[styles.network]
rx_color = "#61afef"
tx_color = "#98c379"
rx_total_color = "#56b6c2"
tx_total_color = "#e5c07b"

[styles.battery]
high_battery_color = "#98c379"
medium_battery_color = "#e5c07b"
low_battery_color = "#e06c75"

[styles.tables]
headers = { color = "#61afef", bold = true }

[styles.graphs]
graph_color = "#5c6370"
legend_text = { color = "#5c6370" }

[styles.widgets]
border_color = "#3e4451"
selected_border_color = "#61afef"
widget_title = { color = "#61afef", bold = true }
text = { color = "#abb2bf" }
selected_text = { color = "#1f2329", bg_color = "#61afef", bold = true }
disabled_text = { color = "#5c6370" }

thread_text = { color = "#98c379" }
